resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- serviceaccount.yaml
- httpscaledobject.yaml
- service-keda.yaml

commonLabels:
  app.kubernetes.io/name: hello

namespace: go-hello

patches:
  - patch: |-
      apiVersion: http.keda.sh/v1alpha1
      kind: HTTPScaledObject
      metadata:
        name: hello
      spec:
        host: hello.0.0.0.0.nip.io

  # TODO: we need to work out how to patch the host
  # - patch: |-
  #     apiVersion: networking.k8s.io/v1
  #     kind: Ingress
  #     metadata:
  #       name: hello
  #     spec:
  #       rules:
  #       - host: hello.0.0.0.0.nip.io